sonar.projectKey=shaheer1107_muhammad_shaheer_khan-mern-10pshine
sonar.organization=shaheer1107
sonar.projectName=MERN Notes App
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**
sonar.sourceEncoding=UTF-8