sonar.organization=Shaheer1107
sonar.projectKey=Shaheer1107_muhammad_shaheer_khan-mern-10pshine
sonar.projectName=MERN Notes App
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**
sonar.sourceEncoding=UTF-8